name: deploy
on:
  push:
    branches:
      - feat/split-workflow
jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Upload node_modules folder
        uses: actions/upload-artifact@v2
        with:
          name: node_modules
          path: node_modules

  build:
    name: Build application
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node and NPM
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Download node_modules
        uses: actions/download-artifact@v2
        with:
          name: node_modules
      - name: Build application
        run: npm run build --if-present
        env:
          PUBLIC_URL: /scales-cheatsheet
      - name: Upload build folder
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  publish:
    name: Publish to gh-pages
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download build folder
        uses: actions/download-artifact@v2
        with:
          name: build
      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build




